vars:
  push_pckt_type: "udp"
  push_trg_type:  "change"
  push_tcp_ip:   "10.37.30.10"
  push_tcp_port: 5050
  push_udp_ip:   "10.37.30.10"
  push_udp_port: 5050 
  hash: 46e42b867f5573ffa950ac2bd2f31352c221b34b04eb7822ce81e386f882370b
  host_port:  80
  ni: 2
controllers:
  - controller: PLB-Mock-1
    config_template: is-plb-test.yml.j2
    vars:
      host_ip:   "localhost"
      host_port:  8080
      resource_id: "PLB-Mock-1"

  - controller: PLB-Test-2
    config_template: is-plb-test.yml.j2
    vars:
      host_ip:   "10.37.28.10"
      resource_id: "PLB-Test-2"
      
  - controller: PLB-Test-3
    config_template: is-plb-test.yml.j2
    vars:
      host_ip:   "10.37.28.133"      
      resource_id: "PLB-Test-3"

  - controller: IS-PLB-84100013-P10
    config_template: polabs_templates/is-plb-84100001-x.yml.j2
    specific_config: polabs_templates/is-plb-84100001-11_10.yml.j2
    vars:
      host_ip:   "10.37.28.12"
      host_port:  80
      resource_id: "STA-8400-84100013-P10"

  - controller: IS-PLB-84100013-P11
    config_template: polabs_templates/is-plb-84100001-x.yml.j2
    specific_config: polabs_templates/is-plb-84100001-11_10.yml.j2
    vars:
      host_ip:   "10.37.28.11"
      host_port:  80
      resource_id: "STA-8400-84100013-P11"

  # 10.37.28.134	4c71.6750.0005		EM42-A	84100013	P12
  - controller: IS-PLB-84100013-P12
    config_template: polabs_templates/is-plb-84100001-x.yml.j2  
    vars:
      host_ip:  "10.37.28.134" 
      host_port:  80
      resource_id: "STA-8400-84100013-P12"

  # 10.37.28.15	4c71.6750.0022		EM42-A	84100013	P4
  - controller: IS-PLB-84100013-P4
    config_template: polabs_templates/is-plb-84100001-x.yml.j2  
    vars:
      host_ip: "10.37.28.15"  
      host_port:  80
      resource_id: "STA-8400-84100013-P4"

  # 10.37.28.14	4c71.6750.0028		EM42-A	84100013	P5
  - controller: IS-PLB-84100013-P5
    config_template: polabs_templates/is-plb-84100001-x.yml.j2  
    vars:
      host_ip:  "10.37.28.14"
      host_port:  80
      resource_id: "STA-8400-84100013-P5"

  # 10.37.28.16	4c71.6750.0029		EM42-A	84100013	P3
  - controller: IS-PLB-84100013-P3
    config_template: polabs_templates/is-plb-84100001-x.yml.j2  
    vars:
      host_ip:  "10.37.28.16"
      host_port:  80
      resource_id: "STA-8400-84100013-P3"

  # 10.37.28.17	4c71.6750.0027		EM42-A	84100013	P1
  - controller: IS-PLB-84100013-P1
    config_template: polabs_templates/is-plb-84100001-x.yml.j2  
    vars:
      host_ip: "10.37.28.17"
      host_port:  80
      resource_id: "STA-8400-84100013-P1"

  # 10.37.28.13	4c71.6750.002a		EM42-A	84100013	P8
  - controller: IS-PLB-84100013-P8
    config_template: polabs_templates/is-plb-84100001-x.yml.j2  
    vars:
      host_ip: "10.37.28.13"
      host_port:  80
      resource_id: "STA-8400-84100013-P8"

  # 10.37.28.135	4c71.6750.002b		EM42-A	84100013	P7	sipod-b0sw2	Gi1/9
  - controller: IS-PLB-84100013-P7
    config_template: polabs_templates/is-plb-84100001-x.yml.j2  
    vars:
      host_ip: "10.37.28.135"
      host_port:  80
      resource_id: "STA-8400-84100013-P7"
  