---
path:
  - "info"
  - "meta"
  - "config/push"
  - "config/io"
  - "system/network"
  - "system/dns"
  - "system/sntp"

sources:
  - name: test-1
    ip:   10.37.28.132
    port: 80

  - name: test-2
    ip:   10.37.28.10
    port: 80
    
  - name: test-3
    ip:   10.37.28.133
    port: 80

  - name: IS-PLB-84100013-P10
    ip:   10.37.28.12
    port: 80

  - name: IS-PLB-84100013-P11
    ip:   10.37.28.11
    port: 80
    
  - name: IS-PLB-84100013-P12
    ip:   10.37.28.135
    port: 80