---
vars:
    SCRAPE_PERIOD_MIN: 5    
    RETRIES: 3
    
path:
  - "info"
  - "meta"
  - "config/push"
  - "config/io"
  - "system/network"
  - "system/dns"
  - "system/sntp"
  - "system/time"

sources:
  - name: test-2
    resource_id: test-2
    source_id: PLB:10.37.28.10
    ip:   10.37.28.10
    port: 80
    
  - name: test-3
    resource_id: test-3
    source_id: PLB:10.37.28.133
    ip:   10.37.28.133
    port: 80

  - name: test-1
    resource_id: test-1
    source_id: PLB:10.37.28.135
    ip:   10.37.28.135
    port: 80

  - name: IS-PLB-84100013-P10
    resource_id: STA-8400-84100013-P10
    source_id: PLB:10.37.28.12
    ip:   10.37.28.12
    port: 80

  - name: IS-PLB-84100013-P11
    resource_id: STA-8400-84100013-P11
    source_id: PLB:10.37.28.11
    ip:   10.37.28.11
    port: 80
    
  - name: IS-PLB-84100013-P12
    resource_id: STA-8400-84100013-P12
    source_id: PLB:10.37.28.134
    ip:   10.37.28.134
    port: 80
