---
path:
  - "info"
  - "meta"
  - "config/push"
  - "config/io"
  - "system/network"

sources:
  - name: test-1
    ip:   10.37.28.132
    port: 80

  - name: test-2
    ip:   10.37.28.10
    port: 80
    
  - name: test-3
    ip:   10.37.28.133
    port: 80    